site_name: Atlas
site_description: A catalog of all the applications and services I maintain
site_author: Akashdeep Dhar
site_url: https://atlasdoc.netlify.app
theme:
  name: lumen
nav:
  - Start here: index.md
  - Applications:
      - NFA-String Parser: apps_nfasp.md
      - RE2FA Converter: apps_re2fa.md
      - Pignus FVD: apps_pgfvd.md
      - Pignus AIP: apps_pgaip.md
      - Super Mario: apps_oglmr.md
      - ToxicIMS: apps_txims.md
      - Foliage: apps_folqt.md
      - Wisdom: apps_wdmqt.md
      - PharmaDB Client: apps_tkpcl.md
      - PharmaDB Store: apps_tkpst.md
  - Services:
      - Sanctuary: sctry.md
      - FORGE: forge.md
      - SPEED: speed.md
      - Data Extraction: dextr.md
  - About me: about.md