site_name: Atlas
site_description: A catalog of all the applications and services I build
site_author: Akashdeep Dhar
site_url: https://atlasdoc.netlify.app
theme:
  name: material
  palette:
    primary: teal
    accent: teal
nav:
    - Start here: index.md
    - About me: about.md
    - NFA-String Parser: nfasp.md
    - RE2FA Convertor: re2fa.md
    - SPEED: speed.md
    - Sanctuary: sctry.md
    - FORGE: forge.md
    - Data Extraction: dextr.md
    - Inquizition: inqzt.md
    - Pignus FVD: pgfvd.md
    - Pignus AIP: pgaip.md
    - Super Mario: oglmr.md
    - ToxicIMS: txims.md
    - Foliage: folqt.md
    - Wisdom: wdmqt.md
    - PharmaDB Client: tkpcl.md
    - PharmaDB Store: tkpst.md