site_name: Atlas
site_description: A catalog of all the applications and services I maintain
site_author: Akashdeep Dhar
site_url: https://atlasdoc.netlify.app
theme:
  name: lumen
nav:
  - Start here: index.md
  - Applications:
      - NFA-String Parser: nfasp.md
      - RE2FA Converter: re2fa.md
      - Pignus FVD: pgfvd.md
      - Pignus AIP: pgaip.md
      - Super Mario: oglmr.md
      - ToxicIMS: txims.md
      - Foliage: folqt.md
      - Wisdom: wdmqt.md
      - PharmaDB Client: tkpcl.md
      - PharmaDB Store: tkpst.md
  - Services:
      - Sanctuary: serv_sctry.md
      - FORGE: serv_forge.md
      - SPEED: serv_speed.md
      - Data Extraction: serv_dextr.md
  - About me: about.md